### ISSUE TITLE
Add a feature to use Docker Model as Provider

### ISSUE THREAD

**Issue by initcron** [docker-aiml/localgpt#1]
this is a sample code 

```
services:
  ai-runner:
    provider:
      type: model  # Looks for docker-model plugin or model binary
      options:
        model: ai/example-model
```
